[library]
crate-type = ["lib"]
name = "moisty"
version = "0.1.0"
edition = "2021"
description="Library for swimming applications"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["jechsoft", "moisty"]
